import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from "../components/Header";
import bg from "../img/background.jpg"
import xibalba from "../img/xibalba.png"
import {useEffect, useState} from "react";
import {number} from "prop-types";
import Cartanatal from "../components/cartanatal";
import Transitos from "../components/transitos";

const Home: NextPage = () => {
	const options = [{name: "Carta natal", focus: true, component:<Cartanatal/>}, {name: "Transitos", focus: false, component: <Transitos/>}, {
		name: "Revolucion Solar",
		focus: false
	}, {name: "Progessiones solares", focus: false},
		{name: "Sinastria draconica", focus: false}]
	const [currOption, useOpt] = useState<boolean[]>([]), [currFocus, setFocus] = useState<number>(0)

	function SwitchTool(tool: number, focus: boolean) {
		currOption[tool] = focus
		currOption[currFocus] = !focus
		setFocus(tool)
		useOpt(currOption)
	}

	useEffect(function Init() {

		options.forEach(x => currOption?.push(false))
		currOption[0] = true
		useOpt(currOption)
	}, [])

	function switchParams() {

	}
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>

			<main className={" h-[100%] w-[100%]"}>
				<div className={"flex shadow-lg"}>
					<div className={"w-[25%] flex border-r"}>
						<Image src={xibalba} height={82} width={82}/>

						<h1 className={"text-3xl font-thin text-center mt-5"}>XIBALBA</h1>

					</div>
					<div className={"w-[75%] flex flex-col justify-center"}>
						<div className={"flex justify-evenly -[50%] m-auto"}>
							{options.map((option, index) => <>{currOption[index] ?
								<p className={"text-lg font-thin border-b border-gray-700 m-2"}>{option.name.toUpperCase()}</p>
								: <p onClick={() => {
									SwitchTool(index, true)
								}}
									 className={"text-base font-light m-2 mt-[0.7rem] cursor-pointer select-none hover:bg-black hover:text-white hover:p-2 transition-all hover:mb-0"}>{option.name.toUpperCase()}</p>
							}</>)}

						</div>
					</div>

				</div>
				<div>
					{options[currFocus].component}
				</div>
			</main>

			<footer className={styles.footer + " bottom-0 fixed w-[100%]"}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
				</a>
			</footer>
		</div>
	)
}

export default Home
